data <- read.csv("household_power_consumption.txt", sep=';',na.strings = c('?'), stringsAsFactors = FALSE)
data <- transform(data, Time = strptime(paste(Date,Time), "%d/%m/%Y %H:%M:%S"))
data <- transform(data, Date = as.Date(Date, "%d/%m/%Y"))
data <- subset(data, Date >= "2007-2-1" & Date <= "2007-2-2")
png(file="Plot3.png")
plot(data$Time, data$Sub_metering_1, type="l", xlab = "", ylab = "Energy sub metering")
points(data$Time, data$Sub_metering_2, type="l", xlab = "", ylab = "Energy sub metering", col="red")
points(data$Time, data$Sub_metering_3, type="l", xlab = "", ylab = "Energy sub metering", col="blue")
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
