#data <- read.csv("household_power_consumption.txt", sep=';',na.strings = c('?'), stringsAsFactors = FALSE)
#data <- transform(data, Date = as.Date(Date, "%d/%m/%Y"))
#data <- transform(data, Time = strptime(Time, "%H:%M:%S"))
sub <- subset(data, Date >= "2007-2-1" & Date <= "2007-2-2")
png(file="Plot1.png")
hist(sub$Global_active_power, main="Global Active Power", col="red", xlab="Global Active Power (kilowatts)")
dev.off()
